### ISSUE TITLE
how to create task xml files?

### ISSUE THREAD

**Issue by leafney** [ljja/SmartSpiderCore#1]
从博客园看到的这个爬虫框架，暂时没有细看实现原理，不过Task下的xml文件光写出来就应该挺耗精力的吧？

**Comment by smartbooks** [comment]
定向采集本身就是一件比较繁琐的事情，能用一个通用的规则引擎完成90%以上的抓取任务，已经是做到极致了。xml文件采集规则编写时必不可少的，后期发展只能云上发展了。不过一般的抓取任务，熟练后的话，写一个抓取规则也就几分钟的事情。

**Comment by leafney** [comment]
@smartbooks  tks
